TURN_FLAG = 1
BACKWARDS_FLAG = 2
OTHER_FLAG = 0

MAX_SPEED_RATE = 24.0

LEFT_WHEEL_FACTOR = 0.65 

END_LINE = -1

LEFT = -1
RIGHT = 1

## --------------- Personalizable constants --------------- ##

INITIAL_WAIT = 5
SENSOR_READ_DELAY = 0.2

# Basic speed
FORWARD_SPEED = 60
BACKWARD_SPEED = 40

# Car acceleration
ACC_RATE = 2
ACC_TIME = 0.2

# Obstacle sensor range
SENSOR_FAR_RANGE = 20
SENSOR_CLOSE_RANGE = 13

# Line follower references 
LINE_REFERENCES = [99, 118, 124, 129, 112] 
LINE_STEP = [2, 7, 10, 20]
LINE_OFF_TRACK_COUNT = 3

# Intense virage angle
TURNING_ANGLE = 40

# Obstacle avoidance 
AVOIDANCE_TURN_TIME = 1
AVOIDANCE_STRAIGHT_TIME_EX = 0.1
AVOIDANCE_STRAIGHT_TIME_MID = 0.7

AVOIDANCE_RIGHT_ANGLE = 128
AVOIDANCE_LEFT_ANGLE = 50

AVOIDANCE_TURN_SPEED = 40

AVOIDANCE_STOP_TIME = 2
AVOIDANCE_BACKWARDS_DIST = 22

# DRIFT
DRIFT_MASTER_WHEEL_SPEED = 60
DRIFT_PIVOT_WHEEL_SPEED = 35
DRIFT_START_COUNT = 7


